### ISSUE TITLE
Set the account id manually by code

### ISSUE THREAD

**Issue by foxpcteam** [googleanalytics/ga-dev-tools#112]
Hi,
Thanks for the great project!

i am using the the real time active users from here:
https://ga-dev-tools.appspot.com/embed-api/third-party-visualizations/

all works great but i have questions.

if it possible to get the data from some account id by manually set the account id by code?

lets say i have 90 accounts in my google analytics account.

i don't want each time when my page loaded, to select the account from the account list that i want to see his data.

also if i can set the account id manually by code how not to show all accounts list field?

Thanks

**Comment by laurenancona** [comment]
@foxpcteam You could just omit the [ViewSelector2](https://github.com/googleanalytics/ga-dev-tools/blob/master/templates/embed-api/third-party-visualizations.html#L95) component from the layout & [javascript](https://github.com/googleanalytics/ga-dev-tools/blob/master/templates/embed-api/code/_third-party-visualizations.js#L54). You'd then need to manually define the view's Table ID (`ids`) for each chart (or with a global variable). 

[Example from documentation](https://developers.google.com/analytics/devguides/reporting/embed/v1/component-reference#datachart-example)

So place of the view selector you could replace [those lines](https://github.com/googleanalytics/ga-dev-tools/blob/master/templates/embed-api/code/_third-party-visualizations.js#L54-L57) with
`var ids = ga:1234567;` in the javascript for the 3rd Party Embed demo.

You can find the `ids` via the [Account Explorer](https://ga-dev-tools.appspot.com/account-explorer/).

@philipwalton - could you confirm that `ids` is unique & you wouldn't need to otherwise define `property id`, etc, after authentication?

**Comment by foxpcteam** [comment]
Hi @laurenancona ,
what about the activeUsers?
where i can set here the ids = ga:1234567;

  var activeUsers = new gapi.analytics.ext.ActiveUsers({
    container: 'active-users-container',
    pollingInterval: 5
  });

Thanks for help!

**Comment by philipwalton** [comment]
@foxpcteam you can pass the `ids` option to the `ActiveUsers` constructor. E.g:

```js
var activeUsers = new gapi.analytics.ext.ActiveUsers({
  ids: 'ga:1234567',
  container: 'active-users-container',
  pollingInterval: 5
});
```

Also, in the future, please ask implementation questions on Stack Overflow using the tag [[google-analytics]](http://stackoverflow.com/questions/tagged/google-analytics). If you're ever unsure where best to ask your Google Analytics questions, refer to [developers.google.com/analytics/help](https://developers.google.com/analytics/help)

@laurenancona yes, `ids` values are unique.
