### ISSUE TITLE
This app tried to access sensitive info in your Google Account. To keep your account safe, Google blocked this access

### ISSUE THREAD

**Issue by randyunger** [googleanalytics/ga-dev-tools#1136]
**What page is this happening on**
https://ga-dev-tools.web.app/ga4/event-builder/

**Describe the bug**
Cannot login, due to "This app is blocked This app tried to access sensitive info in your Google Account. To keep your account safe, Google blocked this access."

**To Reproduce**
1. Go to https://ga-dev-tools.web.app/ga4/event-builder/
2. Click on Login
3. Login
4. See error:  "This app is blocked This app tried to access sensitive info in your Google Account. To keep your account safe, Google blocked this access."

**Expected behavior**
Logged in

**Desktop (please complete the following information):**
 - OS: Windows
- Chrome
-  - Version [e.g. 22]

**Comment by edstros** [comment]
**What page is this happening on**
Copy the URL of the page this issue is happening on. 
https://ga-dev-tools.web.app/ga4/query-explorer/
**Describe the bug**
A clear and concise description of what the bug is.
The page instructs me to be logged in to use the query explorer tool. When selecting an account I am logged into, a popup dialog tells me that the app is blocked. 
**To Reproduce**
Steps to reproduce the behavior:
1. Go to 'https://ga-dev-tools.web.app/ga4/query-explorer/'
2. Click on 'LOGIN'
3. ~~Scroll down to~~ 'Select Google account that you already are logged into'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.
Log in and use the tool

**Screenshots**
If applicable, add screenshots to help explain your problem.
https://recordit.co/VevJfARQ01

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Big Sur
 - Browser [e.g. chrome, safari] Chrome 
 - Version [e.g. 22]Version 109.0.5414.119

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

**Comment by TheRealVincentVanGogh** [comment]
Hey everyone, I have a workaround posted in #1131
