### ISSUE TITLE
GA query explorer and other tools not working

### ISSUE THREAD

**Issue by isurunuwan001** [googleanalytics/ga-dev-tools#1168]
When I try to open query explorer it's showing
"Login status could not be determined. Please ensure cookies are enabled."
![Screenshot](https://user-images.githubusercontent.com/124419422/216749319-ab47cb11-7fa7-41f5-aac4-79b59f3e1fe1.png)

https://ga-dev-tools.web.app/query-explorer/

Same issue with rest of the tools

**Comment by UncleJey** [comment]
same issue. But i think support is alredy dead

**Comment by lehieu2903** [comment]
I'm here because the "The request's dimensions & metrics are incompatible" error. I've seen the log in dev tool. Definitely not because of the cookie and stuff. I think it is probably due to one of the following reasons:

- The project in Google cloud is removed.
- Someone messed up the url.
- Someone dev with other Google cred and plush the dev cred to the production so the url is not matched anymore.

Hope they fix it soon

**Comment by sandinof** [comment]
same issue here, I did try with a different browser but the error still happening, not a cookies problem

**Comment by cjulliancaptain** [comment]
same here... it's been a few days now!
