### ISSUE TITLE
Query Explorer - inconsistent results

### ISSUE THREAD

**Issue by AM12345678** [googleanalytics/ga-dev-tools#124]
Hello,

I am using Query Explorer to pull data for different profiles.
I was comparing the results I got on September 30th 2015 with the results I am getting now - November 2nd 2015.
The "not set" sessions values are way much different.

For example:
I pulled the data for 2013-09-01
Results pulled on September 30th 2015: 120 "not set" sessions
Results pulled on November 2nd 2015: 1930 "not set" sessions 

This happens for all the profiles and all the dates.
I noticed the overall number of sessions is the same (sum of all sessions for all metros).
However the number of sessions per metro is different now... so it looks like the "not set" sessions is way much bigger and then each metro has less sessions than before.

Any idea what is causing this issue?  
Is there a way to fix this issue?
My application is supposed to go live very soon and now I have all these discrepancies out of the blue.

Please help.

**Comment by AM12345678** [comment]
So now everything between 2013-07-01 and 2015-10-12 is off.. 
I don't understand what happened....

**Comment by philipwalton** [comment]
It's not clear to me what your exact issue is or what, specifically, is inconsistent. But either way, it doesn't sound like the problem is with the Query Explorer, since all it does is visually show the data returned by the API.

If the API is giving you inconsistent results, you should report them to the GA issue tracker:
https://code.google.com/p/analytics-issues/issues/entry
