### ISSUE TITLE
Cannot Use app because fail to see login status all cookies are allowed

### ISSUE THREAD

**Issue by lscjean** [googleanalytics/ga-dev-tools#1261]
**What page is this happening on**
Copy the URL of the page this issue is happening on. 

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by DainsAcc** [comment]
**What page is this happening on**
[Copy the URL of the page this issue is happening on. ](https://ga-dev-tools.web.app/ga4/dimensions-metrics-explorer/)

**Describe the bug**
A clear and concise description of what the bug is.
Login status could not be determined. Please ensure cookies are enabled.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to 'above page'
2. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

See page content

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 11 Enterprise
 - Browser [e.g. chrome, safari] Chrome 
 - Version [e.g. 22] version 110.0.5481.78 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.
Happens on these pages as well

https://ga-dev-tools.web.app/ga4/event-builder/
https://ga-dev-tools.web.app/ga4/query-explorer/
