### ISSUE TITLE
Add support for Reporting API v4

### ISSUE THREAD

**Issue by naltmann** [googleanalytics/ga-dev-tools#187]
It looks like the meta data API is auto-completing fields like ga:acquisitionCampaign, but these are marked as not valid by the interface.

**Comment by philipwalton** [comment]
Thanks, this particular issue was fixed via #188 and released in version 16.0.0.

As for general support for the new reporting API version. That's planned, but it's not entirely clear if it can work as a tool like the Query Explorer since it's quite a bit more complicated and full-featured. It will probably end up being more of just a query builder of some sort (rather than a reporting tool), but we're still discussing it internally.
