### ISSUE TITLE
Campaign URL Builder - Campaign Medium is required field

### ISSUE THREAD

**Issue by lacos80** [googleanalytics/ga-dev-tools#235]
If you don't fill Campaign Medium, you will not see anything in GA, no campaign is tracked then, Checked now. I spent couple hours of debugging and finding what is wrong. Just one star in campaign builder.

**Comment by philipwalton** [comment]
This is not true, when you don't set a medium, you will just see "(not set)" in your reports. The campaign source is still tracked.

I've verified this myself several times, as a number of people have asked about it since the previous Campaign URL Builder tool listed medium and name as required fields (which they're not).

**Comment by jarnoudt** [comment]
Just adding to this: 
From my experience, if you don't use Medium, you won't see it correctly in the Real-Time report, but it will come in as (not set) for Medium in the normal reports, as Philip mentioned.

**Comment by lacos80** [comment]
yes.. i agree now, it was confusing but works as described by jarnoudt and philipwalton

**Comment by hyz901214** [comment]
I still think you should use the Campaign Medium,if you donn't use the Medium, the Channels reports will appear the Others,then ,you should edit the Default Channel Grouping1's rule, and the Campaing report will couldn't get the data
