### ISSUE TITLE
New Campaign URL Builder error

### ISSUE THREAD

**Issue by nmbrown** [googleanalytics/ga-dev-tools#248]
I'm finding this tool gives an error if there is a ? already in the website url

For example if I put http://www.wexphotographic.com/?/top-deals.html in the Website URL field, and youtube in the Campaign Source, the output is http://www.wexphotographic.com/?%2Ftop-deals.html=&utm_source=youtube

This isn't a valid url - it defaults back to the homepage. The tool seems to have inserted an extra = before the first &, removing that gives the correct url with tags.

**Comment by philipwalton** [comment]
http://www.wexphotographic.com/?%2Ftop-deals.html=&utm_source=youtube is a valid URL, it just has the slash encoded (which is should, since that's a reserved character in query params).

If your site don't handle that URL then the problem is with your site. It should be configured to decode the encoded query params.

Also, FWIW, you might want to reconsider your URL structure, as it looks like you're using URL params to do routing, which is partly why you're encountering this issue in the first place.
