### ISSUE TITLE
Query explorer no volvio a dar datos sobre eventos unicos en google analytics

### ISSUE THREAD

**Issue by Oscar9011** [googleanalytics/ga-dev-tools#250]
Hola,

Antes query explorer mostraba datos de eventos únicos dentro de la selección de métricas, pero últimamente no ha vuelto a dar esta información.

que podría hacer para obtener esta información si es posible.?

![query explorer google analytics demos tools - google chrome](https://cloud.githubusercontent.com/assets/22621076/20434672/eaa28770-ad76-11e6-8531-6e2c36203688.jpg)

**Comment by philipwalton** [comment]
Thanks for the report. The old `ga:uniqueEvents` metric has been renamed to `ga:uniqueDimensionCombinations`. You can read more about that here:
https://support.google.com/analytics/answer/7084499

The new metric is temporarily marked as deprecated so API users will be made aware of this change. I'll update the Query Explorer though to list it since I see no harm in doing so.

**Comment by philipwalton** [comment]
I've updated the Query Explorer to include `ga:uniqueEvents` via 5da68bbb2b024d2b40c4d92f81619c6682e6a24f.
