### ISSUE TITLE
Cannot access Ga-tool

### ISSUE THREAD

**Issue by jjtao** [googleanalytics/ga-dev-tools#251]
Good day, I have attempted to access the URL Campaign Builder, however the form is no longer appearing. Have cleared cache and tried Chrome and Firefox.

[https://ga-dev-tools.appspot.com/campaign-url-builder/](url)

![googlebroken](https://cloud.githubusercontent.com/assets/23655372/20522854/fdc28ee4-b0ba-11e6-96cd-2cbafb81a9a5.png)

**Comment by philipwalton** [comment]
Are you seeing any errors in your JavaScript console?

**Comment by jjtao** [comment]
I do not know how to use that :(

**Comment by philipwalton** [comment]
If you're using Chrome you can go to "View" > "Developer" > "JavaScript Console". If you see any errors (they'll show up in red), then let me know what they are.

The tool works fine for me and (according to our analytics) lots of other people too, so if you're having issues it's most likely due to a configuration or conflicting browser extension on your computer.

**Comment by jjtao** [comment]
AH thank you! See below error.

Uncaught TypeError: e[s].trim is not a function(…)

**Comment by philipwalton** [comment]
Thanks, that's helpful. It looks like what most likely happened is somehow your locally stored data got corrupted, and the tool was erroring when trying to read it back.

I've made some small updates to catch these types of errors, and I think it should work now. Let me know if you're still see errors.
