### ISSUE TITLE
Disabling third-party cookies causes infinite loading

### ISSUE THREAD

**Issue by StephanBijzitter** [googleanalytics/ga-dev-tools#284]
I clicked the link on this Twitter status:
https://twitter.com/philwalton/status/846388040972955648

The page loads, but the loader indicator goes into indeterminate mode and displays an overlay on top of the content. The content is still readable, but I cannot do anything else.

Console output:
```
Failed to load resource: net::ERR_BLOCKED_BY_ADBLOCKER
apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.nl.EeIfFEVAMLc.O/m=analyti…1/d=1/ed=1/am=AQ/rs=AGLTcCPuRBMjCER49SRuNsd4TQDr8zX-NA/cb=gapi.loaded_0:69 Uncaught Object
app.js:1 Uncaught TypeError: Cannot read property 'name' of null
    at m (app.js:1)
    at app.js:1
```

Running Opera's built-in adblocker and uBlock origin
https://addons.opera.com/en/extensions/details/ublock/

Disabling the adblockers, the following issue appears:

**Comment by philipwalton** [comment]
Well, this tool requires the user to authenticate via oauth to their Google account to view their Google Analytics data, so if you're blocking apis.google.com, you won't be able to use it.

I get that it's a frustrating UX to have the site not work and you not know why. I took at look at the auth library I'm using and it looks like there's a bug where it's not propagating the error handler generated by the underlying Google sign-in library, which means unfortunately there's not much I can do until that bug is fixed (I'll keep this issue open as a reminder).

Regardless, I think you'll have to turn off that setting or whitelist this tool's URL to use it.

**Comment by Lucretiel** [comment]
Upon investigation, it seems like [these error handlers](https://github.com/googleanalytics/ga-dev-tools/blob/94930ea38d80c2f63ebb653386167c8fca78130c/templates/user-auth.html#L23-L35) should be firing when auth fails due to a cookie issue. I'll check and see if there's a bug report in the relevant embed API components.
