### ISSUE TITLE
Even when Event Category and Event Action are empty, Hit can be valid on Hit Builder

### ISSUE THREAD

**Issue by watarumohawk** [googleanalytics/ga-dev-tools#292]
Event Category and Event Action are required for Event Hits as the developer doc says below, but Hit can be valid even when they are empty on Hit Builder. 

https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#events

EXPECTED BEHAVIOR:

    When Event Category and Event Action are empty, Event Hit is not valid on Hit Builder.

ACTUAL BEHAVIOR:

    Even when Event Category and Event Action are empty, Event Hit can be valid on Hit Builder.

STEPS TO REPRODUCE:

1. Set the following parameters

~~~~~

v: 1
t: event
tid: UA-XXXXX-YY (which you have access)
cid: any string

~~~~~

2. Click 'Validate hit'
3. Confirm you see the UI says 'Hit is valid!'

![screen shot](https://cloud.githubusercontent.com/assets/4612196/25164478/263c4926-250c-11e7-9af6-c84c616bf437.png)

**Comment by philipwalton** [comment]
The Hit Validator uses the logic that the hit processing pipeline uses. It only invalidates hits that would be dropped by the processor, and technically event hits without a category or action are still processed, so in that sense they're valid.

In the docs we say category and action are required because without them, these events wouldn't appear in most of the standard event reports.

In general, it's best to specify at least category and action, even though technically those hits would still be processed.
