### ISSUE TITLE
Access token for Java

### ISSUE THREAD

**Issue by sarankup** [googleanalytics/ga-dev-tools#293]
Hi,

I am developing java (JSP) based application in which I would like to show my own analytics reports. As per the procedure in the below mentioned page,

https://ga-dev-tools.appspot.com/embed-api/server-side-authorization/

If I generate the access token using Python, can I use the access token in my Java application for ever. How login the access token will work. In case of the access-token expires, what am I suppose to do? Please advise.

Thanks in advance.

**Comment by philipwalton** [comment]
It will work for Java since it's just a token, but you can also use the Java client to generate it if you want.

You can read more about how OAuth tokens work here:
https://developers.google.com/identity/protocols/OAuth2

If you have further questions, please ask on Stack Overflow as these issues are for reporting bugs with the site.
