### ISSUE TITLE
Rate Limit Exceeded

### ISSUE THREAD

**Issue by marialvrz** [googleanalytics/ga-dev-tools#351]
Hi!

I'm working as usual with this tool, and suddenly I got an error message that states Rate Limit Exceeded while trying to shorten a link. 

I tried cleaning the cache, and I also tried accessing the tool through another web browser with no luck either time. 

What could it be?

Thanks!

**Comment by Lucretiel** [comment]
It's a well-known issue. The official tracker for it is #310. However, because [goo.gl was deprecated](https://developers.googleblog.com/2018/03/transitioning-google-url-shortener.html), we're working on transitioning to using a different URL shortener, which should resolve the Rate Limit issue. Thanks for the report!
