### ISSUE TITLE
Google Analytics API Call error - "ValueError: tzinfo.utcoffset() returned 1440; must be in -1439 .. 1439"

### ISSUE THREAD

**Issue by STANAPI** [googleanalytics/ga-dev-tools#398]
Hi everyone, I've encountered the below error. It seems that the key error is "ValueError: tzinfo.utcoffset() returned 1440; must be in -1439 .. 1439". 

May I know how do I resolve it? I've attached the python script for this (GA_Thread.py). 
[GA_Thread.py.docx](https://github.com/googleanalytics/ga-dev-tools/files/2376613/GA_Thread.py.docx)

Thank you!

----------------------------------------------------------------------------------
The Google Analytics API Call encountered the following exception: 
Traceback (most recent call last):
  File "C:\STB\STAN_MG_API\Google_Analytics\GA_Thread.py", line 25, in <module>
    execfile('GA_Overall.py')
  File "GA_Overall.py", line 339, in <module>
    main()
  File "GA_Overall.py", line 330, in main
    print_response(response)
  File "GA_Overall.py", line 264, in print_response
    writerow[0] = TimeZone_Convert.utc_to_local(writerow[0])
  File "C:\STB\STAN_MG_API\Google_Analytics\TimeZone_Convert.py", line 14, in utc_to_local
    local_dt = utc_dt_parse.astimezone(local_tz)
ValueError: tzinfo.utcoffset() returned 1440; must be in -1439 .. 1439

**Comment by Lucretiel** [comment]
A few things:

- For security reasons, I can't view a python script that is contained in a docx. Feel free to repost as a `.py` file, or with one of the common code snippet sharing tools: [Github Gist](https://gist.github.com/), [Pastebin](https://pastebin.com/), etc.
- Is this issue related to the [Google Analytics Demos & Tools](https://ga-dev-tools.appspot.com/) site? This github issue tracker is only for issues related to that tool.- 
- This appears to be a support request, rather than a bug report. The best place to make code help requests is on [Stack Overflow](https://stackoverflow.com)

Feel free to comment if your issue is a bug specifically related to the Demos & Tools site and I'll re-open this issue.
