### ISSUE TITLE
No way of using tool anymore with new design

### ISSUE THREAD

**Issue by justislav** [googleanalytics/ga-dev-tools#60]
Used to use very intensivly ga-dev-tools and now I can't stand it anymore

New design is a hell due to:

1. can not SAVE request via share if tool-page came unresponsive => complete loss of my work
2. can not EDIT segment & other fields simple way, now I have to select it with mouse, copy, click on cross, paste & not pressing enter modify it, then press enter or else it'll be cleared => complete loss of my time
3. can not COPY-PASTE data right from report page to my google spreadsheet due to localized data => complete loss of goal of ga-dev-tool

RIP
Justislav Bogevolnov, analyst & expert in GA 
justislav@gmail.com

**Comment by philipwalton** [comment]
I'm sorry to hear that our changes negatively affected your workflow. We make changes based on feature requests and user feedback, so it's good to know what is and isn't working for people.

That being said, I have some questions:

> 1) can not SAVE request via share if tool-page came unresponsive => complete loss of my work

I'm not sure what you mean by this. The new version saves your work as you go, and the old version didn't. This is one of the best features of the new version.

> 2) can not EDIT segment & other fields simple way, now I have to select it with mouse, copy, click on cross, paste & not pressing enter modify it, then press enter or else it'll be cleared => complete loss of my time

This is a legitimate complaint, and unfortunately a limitation of the [select2 plugin](https://select2.github.io/) we're using to create these select fields. Once their version 4.0 is stable, I'll update to use it, and you won't have to copy/paste to enter custom fields or make slight changes to existing fields.

For what it's worth, we didn't make this change lightly. We got many, many requests to make metrics, dimensions, and segments searchable, so that's why we changed it. Overall, most people have been very happy with this change.

> 3) can not COPY-PASTE data right from report page to my google spreadsheet due to localized data => complete loss of goal of ga-dev-tool

I don't think you're correct here. The table is the same as before, the only difference is the CSS that styles it. Copying table data to a Google spreadsheet works just fine and has not changed in the new version.

**Comment by justislav** [comment]
1) if I return to tab I hadn't been using for 15-30min & run query the page goes in endless Loading. So i'm not able to RERUN or SAVE my request params coz in browser's url is anything but my request. And now "share report" appears if only request succeds.
https://dl.dropboxusercontent.com/u/9823550/appcraft/Screenshot%20from%202015-04-10%2022%3A14%3A23.png

2) just give a try to specify ga:goal1Completions instead of "searchable" ga:goalXXCompletions
or try to reorder metrics or dimensions then please don't ask for excuse for the junk plugin

3) Yes, my mistake: copy-paste works well. Just got very scary when got "Mar 31, 2015" instead of foolproof "2015-03-31"... so far... are the dates in en-US locale always?

**Comment by philipwalton** [comment]
> 1) if I return to tab I hadn't been using for 15-30min & run query the page goes in endless Loading. So i'm not able to RERUN or SAVE my request params coz in browser's url is anything but my request. And now "share report" appears if only request succeds.

I see, what's probably happening is your session has expired and your `access_token` is no longer valid. This happens after an hour, and it also happened in the old Query Explorer. I've filed #57 to track improving the error reporting for this case.

For what it's worth, the new Query Explorer saves your state, so if you just refresh all the params you had previously set will be remembered, and you can just continue on without losing your work. In the old Query Explorer, when your session expired, you lost everything.

> are the dates in en-US locale always?

Yes, the API always returns dates in US format, and it always has.

**Comment by philipwalton** [comment]
I'm going to close this issue as there's no specific bug or feature request. If you'd like to request a specific feature or improvement, or if you want to report a bug, feel free to open up another issue.

**Comment by justislav** [comment]
Thank you for the dialog! I wish I could thank you for something usefull for me & my team. E.g. previous hardcore release of ga-dev-tool on maybe some special url. It's OK if it have big warning like "Deprecated! Use it for own risk". And I will *use* it. But not the new one

**Comment by philipwalton** [comment]
This may or may not help you, but on the off chance that it does (or it helps someone else), I wanted to point out that it's still possible to run the old Query Explorer because the source code for all old versions is preserved by git.

Here's what you'd have to do to check out the previous version of the code and run it on your own computer using Google App Engine:

```sh
# Clone the repository.
git clone https://github.com/googleanalytics/ga-dev-tools.git
cd ga-dev-tools

# Checkout a version prior to the recent Query Explorer changes.
git checkout 4.0.1

# Install and build the dependencies.
npm install && npm run build
```

Once you've done this, you can fire up a local App Engine instance (download [App Engine for Python](https://cloud.google.com/appengine/downloads)), and then visit [localhost:8080/explorer/](http://localhost:8080/explorer/) and you'll be able to use the old Query Explorer for as long as you want.
