### ISSUE TITLE
loosing request setup if ga-dev-tool lost token

### ISSUE THREAD

**Issue by justislav** [googleanalytics/ga-dev-tools#61]
After my lunch break I modified request and it went very long "Loading"

I remember you told me in #60 I just need to refresh page in my browser --- so I got setup from URL but not form my latest request

Please consider modifying URL accordingly or making request URL field constantly present

**Comment by philipwalton** [comment]
Thanks, I've definitely encountered this exact problem and have contemplated an appropriate solution for it. There are a couple of concerns about updating the URL with the current query, but I'll leave this issue open as a reminder that it needs to be addressed, and I'll report back here when the issue is resolved.

**Comment by philipwalton** [comment]
This has been fixed as of [7.0.1](https://github.com/googleanalytics/ga-dev-tools/releases/tag/7.0.1).
