### ISSUE TITLE
How to resize Analytics

### ISSUE THREAD

**Issue by shinokada** [googleanalytics/ga-dev-tools#71]
I use the following for Google chart to reload when window resize happens.

    $(window).resize(function(){
      drawTable();
    });

I tried a similar thing for [a basic dashboard](https://ga-dev-tools.appspot.com/embed-api/basic-dashboard/) but it doesn't work. 

    $(window).resize(function(){
      viewSelector.execute();
    });

What is the best way to reload when a window is resized?

Thanks in advance.

**Comment by philipwalton** [comment]
The charts need to be redrawn when the window is resized because they're SVG and render to pixel sizes. The view selector, on the other hand, consists just of HTML elements, so it can be sized with CSS alone. No JavaScript is necessary to resize it when the window size changes.

Here's the CSS being used to style the view selector in the basic dashboard example:
https://github.com/googleanalytics/ga-dev-tools/blob/master/src/css/components/view-selector.css

**Comment by shinokada** [comment]
![dashboard___cecilieo](https://cloud.githubusercontent.com/assets/147320/7996431/3b2106fa-0b5b-11e5-831d-eed90734af17.png)
The image is the basic dashboard. It seems a SVG image. I tried to use the CSS you mentioned but it didn't work.

**Comment by philipwalton** [comment]
You originally asked about the view selector, are you trying to resize it or one of the charts?

**Comment by shinokada** [comment]
I aplogize if my question was not clear.
I am trying to embed [a basic dashboard](https://ga-dev-tools.appspot.com/embed-api/basic-dashboard/) from Embed API.
