### ISSUE TITLE
Query Explorer returning different results to GA

### ISSUE THREAD

**Issue by bonko99** [googleanalytics/ga-dev-tools#723]
**What page is this happening on**
https://ga-dev-tools.web.app/query-explorer/

**Describe the bug**
The results produced by query explorer do not match those seen in GA. This seems to only occur when using segments as it shows the correct data when no segment is used. When used in GA, the segments produce the correct values. When used in Query Explorer, it shows incorrect data.

**To Reproduce**
(Not sure if this is reproducable) Steps to reproduce the behavior:
1. Go to Query Explorer (URL above)
2. Add **ga:users** and **ga:goal1Completions** to the metrics field.
3. Add **ga:year** and **ga:month** to the dimensions field.
4. Set the start date as **2021-06-01**, and the end date **yesterday**.
5. Add a segment, I used **gaid::-4** (Paid Traffic default segment).
6. Run the query and compare results to GA.

**Expected behavior**
Would expect to see a results table with 4 columns (year, month, users, goal completions), and 4 rows (one for each month, June through September), which I do. The row for September that shows the correct month-to-date values i.e. every day in September excluding the current date, which is doesn't.

**Screenshots**
[https://imgur.com/a/5B0mq5D](url)

**Desktop (please complete the following information):**
 - OS: Windows 10 - Version 10.0.19042 Build 19042
 - Browser: Chrome - 93.0.4577.63

**Comment by diminishedprime** [comment]
This issue tracker is for reporting bugs with the code in this repository. Your issue seems to be a general API related issue. You should try to reproduce the issue using the [API Explorer](https://developers.google.com/analytics/devguides/reporting/core/v4/rest/v4/reports/batchGet?apix=true) and contact the [Analytics API support if necessary](https://developers.google.com/analytics/devguides/reporting/core/v4/help#contact-us)
